### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by ssayer** [smart-on-fhir/Swift-FHIR#1]
I think it would be handy to create a cocoapod for this library. In order to do so the code will need the following changes:

* Needs a license file.
* Needs a git tag with the same name as the version. In this case you'd need a tag called 0.0.82.2943.
* Cocoapods for Swift is only supported on iOS 8 and above. The readme currently lists support as iOS7 and above

If you're interested, I'd be glad to submit a pull request with a valid podspec once these issues are cleared up.

**Comment by p2** [comment]
Though I don't use Pods myself currently I should finally start doing so. I haven't been working on the master branch, let's do this on the develop branch. I have been irregularly updating since there's still a lot of movement between commits, I'll add the license and specify the iOS 8 requirement, then tag after the next data model update. Happy to accept a pull request!

Should we do that on the [SMART-on-FHIR](https://github.com/smart-on-fhir/SMART-on-FHIR-Cocoa) client, which is a complete client, or also on this repo?

**Comment by ssayer** [comment]
I think it's worth doing it for this library since it's now linked to as a reference implementation for FHIR (http://hl7-fhir.github.io/downloads.html). Once this is a pod, SMART-on-FHIR could be one too.

Once you've done the above steps, just post an update here and I'll issue a PR with the podfile.

**Comment by p2** [comment]
I've added the license and re-generated the models. From what I hear the latest DSTU-2 version will be dumped to hl7.org/fhir-develop some time next week for the ballot. I think it makes sense to tag that version and then create a podspec for it, what do you think?

**Comment by p2** [comment]
I have added a podspec to the Swift-SMART framework, which includes these FHIR classes but also an implementation of a Server class, needed to truly use the client: https://github.com/smart-on-fhir/Swift-SMART/commit/ae87ed70f024f9a32bdf8dfbb1809738ee821815

**Comment by ssayer** [comment]
I'm working with FHIR, but with a different auth stack than SMART, can I still work with FHIR outside of SMART with the other library? Since this is being linked to from the FHIR docs, there may be other people as well with a similar use case.

If you add a podspec to this repo, you can reference it in Smart on FHIR like so:

spec.dependency 'FHIR', '~> 0.5.0'

**Comment by p2** [comment]
The SMART client has a `Server` class which in turn talks to an `Auth` class that performs all authorization tasks. It auto-detects the OAuth2 extension but also works with no auth, it should be easy to extend/add-a-subclass to support other authorization mechanisms, if that's useful?

The code from this repo is included in the SMART client; a submodule in git but added to the same target (to avoid having to import two different libraries when working with our client). I presume I could make this a pod regardless of how I integrate it in the SMART client, though.

**Comment by p2** [comment]
Pushed to CocoaPods as `FHIR`, hope this works for you!

**Comment by ssayer** [comment]
I'll try it out! Thanks!
