### ISSUE TITLE
Trying to deploy Swift-FHIR to IBM Bluemix.

### ISSUE THREAD

**Issue by scheid** [smart-on-fhir/Swift-FHIR#2]
Hi there. I am interested in using these swift models for a swift api I am creating on the IBM Bluemix platform. Bluemix runs Swift on Ubuntu Linux, and I figured out while trying to deploy swift-fhir to my bluemix app, and getting lots of compile errors, that certain swift functionality and classes on MacOSX are not compatible with Swift on Linux (the most errors seemed to be in DateAndTime.swift).  I did some research and found out: _"Swift programs running on Linux with the Swift Core Libraries use a version of Foundation natively written in Swift, without an Objective-C runtime to bridge to. Since Swift does not interoperate with Objective-C on Linux, there is no support for bridging conversions such as string as NSString or value as AnyObject"_ (quote is from https://developer.apple.com/swift/blog/).  I am wondering if you have any plans to make Swift-FHIR work on Ubuntu?

**Comment by p2** [comment]
Oh interesting, thanks for testing that. I'd definitely be interested in getting this running on Linux.

I have tried to stay Swift-native as much as was convenient and am not bridging to Objective C knowingly (but haven't tested on Linux yet), with one exception: `NSDate`. If you comment out everything about NSDate in that file (including the full `DateNSDateConverter` class), does this solve all errors or are there more?

**Comment by scheid** [comment]
Thank you for the quick reply.  Actually the types of errors are really varied, but oddly enough I did not see any related to NSDate.  I have attached a text file with a sample of the message types I was getting during the IBM Bluemix build:

[bluemix-swiftfhir-messages.txt](https://github.com/smart-on-fhir/Swift-FHIR/files/584891/bluemix-swiftfhir-messages.txt)

The line numbers in those messages will be different than the current master files. Here is the DateAndTime.swift file that matches the messages above:

[DateAndTime.txt](https://github.com/smart-on-fhir/Swift-FHIR/files/584897/DateAndTime.txt)

Note that I wasn't using the client files at the time (only the models), so there may be similar Linux issues with those; I have not checked.  

One change I made that seemed to help is with String formatting.  The current master files have this pattern:

` return String(format: "%02d:%02d:%@", hour, minute, secStr)`

and the error was 

> "does not conform to expected element type 'CVarArg'"

Changing to this pattern seems to resolve that problem on Linux:

 `return String(format: "%02d:%02d:%@", arguments:[hour, minute, secStr])`

The Swift-FHIR project will build successfully in XCode on my Macbook, so it really does seem to be due to Swift on Linux.

**Comment by p2** [comment]
Alright thanks. I have a Ubuntu Xenial VM running now and am getting the same errors. I'm looking into it, the first thing to work around is [SR-957](https://bugs.swift.org/browse/SR-957).

**Comment by p2** [comment]
Second problem: [(NS)Scanner](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSScanner.swift) in CoreLibs/Foundation does not currently have the same interface as the one used on macOS.

**Comment by p2** [comment]
I got the `develop` branch to successfully compile, does it work for you? `swift test` however doesn't work because somehow it doesn't like `import SwiftFHIR`, not sure why that would be different.

Maybe I can just cherry-pick this into the `master` branch, trying...

**Comment by scheid** [comment]
Thanks for the quick fix.  I will check as soon as I can,  which will likely be in a few days.

**Comment by scheid** [comment]
Just cloned the latest and yes, it does compile with no errors for me now.  Thanks!

**Comment by p2** [comment]
I'll reopen this because there is a platform inconsistency in `NSJSONSerialization`, which means that parsing most numbers on Linux will fail. Described in [SR-1610](https://bugs.swift.org/browse/SR-1610).

**Comment by p2** [comment]
Update: the framework now uses custom primitive types, for numeric values that's `FHIRDecimal` and co. As of Swift 3.0.2, Swift Foundation's `Decimal` has not been fully implemented however, hence the current develop branch will not compile.

I tried a workaround using `Double` internally, but the compiler is not happy with the `factory()` method as used in `FHIRAbstractResource.instantiate()`. So, for now, not working (correctly) on Linux.

**Comment by p2** [comment]
Latest Linux update: `develop` now compiles on Linux but a) does not use the factory method in `FHIRAbstractResource.instantiate()` and b) uses a `Decimal` ➔ `Double` conversion involving String.
