### ISSUE TITLE
Canonical URL

### ISSUE THREAD

**Issue by raheelsayeed** [smart-on-fhir/Swift-FHIR#24]
[Canonical URL](https://www.hl7.org/fhir/datatypes.html#canonical):

> A URI that refers to a resource by its canonical URL (resources with a url property). The canonical type differs from a uri in that it has special meaning in this specification, and in that it may have a version appended, separated by a vertical bar (|). Note that the type canonical is not used for the actual canonical URLs that are the target of these references, but for the URIs that refer to them, and may have the version suffix in them. Like other URIs, elements of type canonical may also have #fragment references

The canonical URIs in R4 aren't being handled in [FHIRURL](https://github.com/smart-on-fhir/Swift-FHIR/blob/master/Sources/Models/FHIRURL.swift). Swift's URL does not accept a vertical bar. 

Hence, a uri like `http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire|3.5.0` fails.

Possibly two approaches we can take

1. Add a `let version: String?` to `FHIRURL`, catch the vertical bars on initialization, reassign to `version` 
2. Entirely new class? This is perhaps unnecessary.

Any suggestions?

**Comment by xmlmodeling** [comment]
Hi Raheel,

Yes, I am working on an update to the generator to use a new dedicated
type, FHIRCanonical that is initially a copy of FHIRURL struct (cannot use
inheritance with Swift struct).  The generator is already updated and I am
working on an extension to FHIRCanonical that provides a default
implementation for a resolve() function that is similar to the one on
Reference.  I realize that canonical URIs may not be resolvable, but HL7
recommends that, and the default implementation will attempt to load from
the absolute URL (without version, although the search could be refined to
include version).  I am also considering a protocol that will allow an
application to pre-load definition type resources and then retrieve from
cache using the URI as key.

I had also encountered the error parsing canonical URIs with version
suffix, but forgot about it while working on this update.  I'll add a
'version' property to FHIRCanonical.  I will plan to commit an update to
'develop' branch within the next week.

Will you be at WWDC next month?  If so, would be nice to meet and discuss
these frameworks.

Thanks,
  Dave

**Comment by xmlmodeling** [comment]
I committed an update to Swift-FHIR develop branch with support for FHIR
canonical type.  See FHIRCanonical and FHIRCanonical+Resolving, and
CanonicalTests with unit tests. Canonical references may be resolved from
contained resources or bundled resources using fragment, similar to
Reference.  See:
  https://www.hl7.org/fhir/references.html#canonical-fragments

The URI format with the fragment following the |version suffix required the
fragment to be parsed and stored in FHIRCanonical.  This support for
canonical resolution from fragments can be used with Questionnaire and
canonical references to contained ValueSet, as required by the Argonaut
Questionnaire implementation guide.

I plan to merge this update into the master branch within the next few
days, then update Swift-SMART with this dependency and Swift 5.0.  I want
to have these changes committed to master prior to WWDC on June 3rd.

Comments and improvements welcome!
  Dave Carlson

**Comment by raheelsayeed** [comment]
Perfect! Thanks Dave.

Unfortunately, I won't be at WWDC this year, but will be in DevDays. I'll test this out this week and comment back.
