### ISSUE TITLE
Use of `_summary=true` for `/metadata` will not return OAuth uris

### ISSUE THREAD

**Issue by hansenms** [smart-on-fhir/Swift-FHIR#26]
The SWIFT FHIR client uses summary listing for the capability statement:

https://github.com/smart-on-fhir/Swift-FHIR/blob/master/Sources/Client/FHIROpenServer.swift#L78

Servers are not required or expected to return extensions in summary results. Only HAPI based implementations include these extensions in summary listings (and it appears only in capability statement) at the moment. 

According to: http://hl7.org/fhir/search.html#summary

"There is some question about the inclusion of extensions in the summary. Additional rules may be made around this in the future", so there is at least ambiguity about whether a server will return these extensions and it is clear that it is not required too. 

Consequently summary listing is unreliable as a way to obtain the OAuth URIs.

**Comment by xmlmodeling** [comment]
Fixed with PR.
