### ISSUE TITLE
Converting Apple Watch's ECG Data to a FHIR Observation

### ISSUE THREAD

**Issue by ylboerner** [smart-on-fhir/Swift-FHIR#29]
Hello Ladies and Gentlemen, 

I am currently working on a project which takes raw ECG data (ECGs were taken on the Apple Watch) from an Apple Health export and sends that data to a VONK server. The workflow looks like this: 

Export health data from health app --> Receive data via share extension --> Unzip data --> Read in CSVs --> Create an observation with Swift-FHIR --> Send observation (or resource) to server with Swift-SMART

Steps 1-4 are already implemented. However, I'm having trouble understanding how to create [an observation](http://docs.smarthealthit.org/Swift-SMART/Classes/Observation.html) from the CSVs with the ECG's data. More specifically: 

1. What is the required format for data for an ECG observation?
2. How do I pass the data from the CSV into the observation?

Code examples would be much appreciated. [Here is a gist with a sample CSV of one of the ECGs taken.](https://gist.github.com/ylboerner/1203f26d557083ec732178394d1c394c)

I'm sorry if this is trivial. I'm new to Swift and FHIR and appreciate your help in advance. 

Regards

**Comment by iPsych** [comment]
@ylboerner Hello, could you extract the .csv from apple watch health app?

**Comment by raheelsayeed** [comment]
@ylboerner Perhaps some derivative of this could work? http://build.fhir.org/ig/HL7/PHD/RtsaObservationProfile.html

**Comment by ylboerner** [comment]
@iPsych @raheelsayeed Everything figured out :-) See here: https://github.com/ylboerner/FhirEcg

**Comment by iPsych** [comment]
@ylboerner 
Thanks so much : )

**Comment by charleschoy** [comment]
@ylboerner Regarding your FhirEcg repo, I saw some test ECG data where there are two columns of data. May I know how to interpret these columns? 
Thanks in advance
