### ISSUE TITLE
use empty Arrays to express emptiness

### ISSUE THREAD

**Issue by xinsight** [smart-on-fhir/Swift-FHIR#4]
Most models objects have optional arrays (e.g. Patient.name, Patient.identifier) which leads to two different ways to express emptiness: the array is nil, or the array is empty.

It would be simpler if clients didn't have to check for both types of emptiness, and make the arrays non-optional.

Are there any barriers to making this change?

btw, I'm at the FHIR dev days conference. Are you around?

**Comment by p2** [comment]
There's a few reasons why I'm not a fan of this change.

One is consistency – all properties are optional to enable the `json:` initializers.

Then we'd also need to decide, upon serialization, what to do – never show empty arrays, always show them? With both nil and empty available the dev can take care of this.

And, not least, Swift makes it really easy to deal with nil-ness and emptyness: you can use `guard` and test for nil-ness and emptiness in one line and you can use `map()` and `filter()` over nil and empty arrays easily.

But I'm open for discussion! And I just arrived at the DevDays, yes, so cu around!
