### ISSUE TITLE
Could not find remote branch 2.2 to clone

### ISSUE THREAD

**Issue by devikirankhode** [smart-on-fhir/Swift-FHIR#5]
`pod install:`
**Error:**
[!] Error installing FHIR
[!] /usr/bin/git clone https://github.com/smart-on-fhir/Swift-FHIR.git /var/folders/mq/b_s7ht696vd3xkr6m5qz13ww00134y/T/d20161121-51618-1ey3k3n --single-branch --depth 1 --branch 2.2

warning: Could not find remote branch 2.2 to clone.
fatal: Remote branch 2.2 not found in upstream origin

_My Podfile looks like:_

pod 'AFNetworking', '~> 2.2'
pod 'AFNetworking-RACExtensions', '~> 0.1'
pod 'BlocksKit', '~> 2.2'
pod 'Classy'
pod 'CRToast', '~> 0.0'
pod 'iCarousel', '~> 1.8.1'
pod 'JSONModel'
pod 'MMPReactiveStompClient', '~> 0.2'
pod 'PDKeychainBindingsController', '~> 0.0'
pod 'SocketRocket', '~> 0.4'

use_frameworks!
pod 'FHIR', '2.2'
pod 'Alamofire', '~> 3.0'
pod 'Charts', '~> 2.2'
pod 'JWTDecode', '~> 1.0'
pod 'ObjectMapper', '1.1.5'
pod 'Starscream', '~> 1.1'

target :CertifyHLTests do
    pod 'BlocksKit', '~> 2.2'
end

**Comment by p2** [comment]
Any particular reason you're using `2.2` and not `~> 2.2`, which would use 2.2.4?
